info:
  max_tasks_retries: 5
  pause_between_tasks: "1-3"
  pause_between_accounts: "1-3"
  
  # "0-0" for all accounts
  account_range: "0-0"
      
proxy:
  mobile_proxy: "no"
  change_ip_pause: 5
  